name: Sync Recipes File from External Repo

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite UTC

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Fetch recipes.ts from external repo
        run: |
          curl -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
               -H "Accept: application/vnd.github.v3.raw" \
               -o src/data/recipes.ts \
               https://api.github.com/repos/fernandoeeu-g4/recipes/contents/recipes.ts

      - name: Check for changes
        id: git-check
        run: |
          git add src/data/recipes.ts
          git diff --staged --quiet || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Sync recipes.ts from external repo"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
