name: Sync Recipes File from External Repo

on:
  push:
    branches:
      - main # ou a branch que você deseja monitorar

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Clone external repository
        run: |
          git clone https://github.com/fernandoeeu-g4/recipes.git external-repo

      - name: Copy recipes.ts file
        run: |
          cp external-repo/recipes.ts src/data/recipes.ts
          ls -l src/data/recipes.ts # Verifica se o arquivo foi copiado corretamente

      - name: Check for changes
        run: |
          git diff --exit-code || echo "Changes detected"

      - name: Remove external-repo directory
        run: rm -rf external-repo

      - name: Configure Git
        run: |
          git config --global user.email "fernando.avcouto@gmail.com"
          git config --global user.name "Fernando Couto"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # Certifique-se de que o token tem permissões
        run: |
          git add src/data/recipes.ts
          if ! git diff --cached --exit-code; then
            git commit -m "Sync recipes.ts from external repo"
            git push origin main
          else
            echo "No changes to commit"
          fi
